# Generated by Django 4.0.5 on 2022-06-14 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('edad', models.PositiveIntegerField(verbose_name='Edad (años)')),
                ('fecha', models.DateTimeField(verbose_name='Fecha de nacimiento')),
            ],
        ),
    ]
